channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.0.0
  - numpy==1.26.3
  - packaging==21.3
  - psutil==5.9.4
  - pyyaml==6.0
  - scikit-learn==1.4.0
  - scipy==1.12.0
name: mlflow-env
